# Example configuration file for telescope.
#
# Run telescope as follows:
#
#   ndag-telescope -c <path to your config file>

dagdev: /dev/dag0

darknetoctet: 44

statinterval: 60

statdir: /var/log/ndag

outputs:
  -
    mcastaddr: xx.xx.xx.xx
    mcastport: 44000
    srcaddr: xx.yy.zz.aa
    mtu: 8960
    filterfile: /path/to/filter1
    monitorid: 44
  -
    mcastaddr: yy.yy.yy.yy
    mcastport: 44004
    srcaddr: xx.yy.zz.aa
    mtu: 8961
    filterfile: /path/to/filter2
    monitorid: 45
  -
    mcastaddr: zz.zz.zz.zz
    mcastport: 44008
    srcaddr: xx.yy.zz.aa
    mtu: 8962
    monitorid: 46
  -
    filterfile: /path/to/filter3
    # ^ drop packets
